name: soarql

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  remove-nightly-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove existing nightly tag
        run: |
          gh release delete nightly --cleanup-tag || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-nightly:
    name: Publish nightly binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
              NAME: aarch64-linux,
              TARGET: aarch64-unknown-linux-musl,
            }
          - {
              NAME: loongarch64-linux,
              TARGET: loongarch64-unknown-linux-musl
            }
          - {
              NAME: riscv64-linux,
              TARGET: riscv64gc-unknown-linux-musl
            }
          - {
              NAME: x86_64-linux,
              TARGET: x86_64-unknown-linux-musl,
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version info
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "version=nightly-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends \
            --allow-unauthenticated musl-tools b3sum file

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.build.TARGET }}

      - name: Install Cross
        run: |
          cargo install cross --git "https://github.com/cross-rs/cross" --jobs="$(($(nproc)+1))"
          hash -r &>/dev/null
          command -v cross &>/dev/null || { echo "cross command not found" >&2; exit 1; } 
       
      - name: Build
        env:
          RUSTFLAGS: "-C target-feature=+crt-static \
                      -C default-linker-libraries=yes \
                      -C link-self-contained=yes \
                      -C opt-level=z \
                      -C debuginfo=none \
                      -C strip=symbols \
                      -C link-arg=-Wl,-S \
                      -C link-arg=-Wl,--build-id=none \
                      -C link-arg=-Wl,--discard-all \
                      -C link-arg=-Wl,--strip-all"
        run: RUSTFLAGS="-C target-feature=+crt-static" cross +nightly build --release --locked --target "${{ matrix.build.TARGET }}" --jobs="$(($(nproc)+1))" --verbose

      - name: Prepare nightly binary
        shell: bash
        run: |
          mkdir -p nightly
          cp "target/${{ matrix.build.TARGET }}/release/soarql" nightly/soarql-${{ matrix.build.NAME }}
          b3sum nightly/soarql-${{ matrix.build.NAME }} > nightly/soarql-${{ matrix.build.NAME }}.b3sum
          du -bh nightly/soarql-${{ matrix.build.NAME }}
          file nightly/soarql-${{ matrix.build.NAME }}
          
      - name: Upload nightly binary
        uses: softprops/action-gh-release@v2
        with:
          files: nightly/*
          tag_name: nightly
          name: ${{ steps.version.outputs.version }}
          body: "This is an automated nightly build of soarql."
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
